POST http://localhost:3000/api/cities
Content-Type: application/json

{
  "nombre_ciudad": "Durango",
  "temp_actual": 19,
  "porcentaje_lluvia": 80,
  "temp_prox1": 21,
  "temp_prox2": 20,
  "temp_prox3": 18,
  "temp_prox4": 18,
  "temp_prox5": 20
}

###
POST http://localhost:3000/api/cities
Content-Type: application/json
[{
  "id_ciudad":"",
"nombre_ciudad": "Queretaro",
}]

###
GET http://localhost:3000/api/cities/2